// A1-A2 en sık kullanılan kelimeler — temalara göre, örnek cümleli.
// "Karta ekle" butonu bu cümleyi bağlam olarak SRS'e taşır.

export type VocabWord = { en: string; tr: string; example: string };
export type VocabTheme = { id: string; title: string; words: VocabWord[] };

export const VOCAB_THEMES: VocabTheme[] = [
  {
    id: "verbs-1",
    title: "Temel fiiller 1",
    words: [
      { en: "be", tr: "olmak", example: "I want to be a good developer." },
      { en: "have", tr: "sahip olmak", example: "I have two brothers." },
      { en: "do", tr: "yapmak", example: "What do you do on weekends?" },
      { en: "go", tr: "gitmek", example: "I go to work by bus." },
      { en: "come", tr: "gelmek", example: "Can you come to my house?" },
      { en: "get", tr: "almak, edinmek", example: "I get up at seven every day." },
      { en: "make", tr: "yapmak, üretmek", example: "She makes great coffee." },
      { en: "take", tr: "almak, götürmek", example: "Take an umbrella; it may rain." },
      { en: "give", tr: "vermek", example: "Please give me the keys." },
      { en: "see", tr: "görmek", example: "I see my friends every Friday." },
      { en: "know", tr: "bilmek", example: "I know the answer to this question." },
      { en: "think", tr: "düşünmek", example: "I think English is fun." },
      { en: "want", tr: "istemek", example: "I want to learn English quickly." },
      { en: "need", tr: "ihtiyacı olmak", example: "We need more time for this task." },
      { en: "like", tr: "sevmek, hoşlanmak", example: "I like listening to podcasts." },
    ],
  },
  {
    id: "verbs-2",
    title: "Temel fiiller 2",
    words: [
      { en: "say", tr: "söylemek", example: "What did you say?" },
      { en: "tell", tr: "anlatmak, söylemek", example: "Tell me about your day." },
      { en: "speak", tr: "konuşmak", example: "She speaks English very well." },
      { en: "talk", tr: "konuşmak, sohbet etmek", example: "We talk every evening." },
      { en: "ask", tr: "sormak", example: "Can I ask you a question?" },
      { en: "answer", tr: "cevaplamak", example: "Please answer my message." },
      { en: "work", tr: "çalışmak", example: "I work from home on Fridays." },
      { en: "study", tr: "ders çalışmak", example: "He studies English every morning." },
      { en: "learn", tr: "öğrenmek", example: "You learn faster when you listen." },
      { en: "teach", tr: "öğretmek", example: "She teaches math at a school." },
      { en: "read", tr: "okumak", example: "I read a few pages before bed." },
      { en: "write", tr: "yazmak", example: "Write your name here, please." },
      { en: "listen", tr: "dinlemek", example: "Listen to the music of the language." },
      { en: "watch", tr: "izlemek", example: "We watch a series together." },
      { en: "play", tr: "oynamak, çalmak", example: "The children play in the park." },
    ],
  },
  {
    id: "verbs-3",
    title: "Günlük fiiller",
    words: [
      { en: "eat", tr: "yemek", example: "We eat dinner at eight." },
      { en: "drink", tr: "içmek", example: "I drink two cups of coffee a day." },
      { en: "sleep", tr: "uyumak", example: "I sleep seven hours a night." },
      { en: "wake up", tr: "uyanmak", example: "I wake up early on weekdays." },
      { en: "open", tr: "açmak", example: "Open the window, please." },
      { en: "close", tr: "kapatmak", example: "Close the door behind you." },
      { en: "buy", tr: "satın almak", example: "I need to buy some bread." },
      { en: "pay", tr: "ödemek", example: "Can I pay by card?" },
      { en: "cook", tr: "pişirmek", example: "My father cooks on Sundays." },
      { en: "clean", tr: "temizlemek", example: "I clean the house on Saturdays." },
      { en: "walk", tr: "yürümek", example: "We walk to the park every evening." },
      { en: "run", tr: "koşmak", example: "He runs five kilometers a day." },
      { en: "drive", tr: "araba kullanmak", example: "She drives to work." },
      { en: "wait", tr: "beklemek", example: "Please wait a moment." },
      { en: "help", tr: "yardım etmek", example: "Can you help me with this?" },
    ],
  },
  {
    id: "family",
    title: "Aile ve insanlar",
    words: [
      { en: "family", tr: "aile", example: "My family lives in Denizli." },
      { en: "mother", tr: "anne", example: "My mother is a great cook." },
      { en: "father", tr: "baba", example: "My father works in a factory." },
      { en: "brother", tr: "erkek kardeş", example: "My brother is older than me." },
      { en: "sister", tr: "kız kardeş", example: "My sister lives abroad." },
      { en: "son", tr: "oğul", example: "Their son is three years old." },
      { en: "daughter", tr: "kız evlat", example: "Her daughter goes to school." },
      { en: "husband", tr: "koca, eş", example: "Her husband is a doctor." },
      { en: "wife", tr: "karı, eş", example: "His wife works at a bank." },
      { en: "child", tr: "çocuk", example: "Every child needs love." },
      { en: "friend", tr: "arkadaş", example: "He is my best friend." },
      { en: "neighbor", tr: "komşu", example: "Our neighbor is very kind." },
      { en: "people", tr: "insanlar", example: "Many people use this app." },
    ],
  },
  {
    id: "time",
    title: "Zaman",
    words: [
      { en: "time", tr: "zaman", example: "What time is it?" },
      { en: "day", tr: "gün", example: "Have a nice day!" },
      { en: "week", tr: "hafta", example: "See you next week." },
      { en: "month", tr: "ay", example: "I start a new job next month." },
      { en: "year", tr: "yıl", example: "This year I will learn English." },
      { en: "today", tr: "bugün", example: "Today is a good day to start." },
      { en: "tomorrow", tr: "yarın", example: "The meeting is tomorrow morning." },
      { en: "yesterday", tr: "dün", example: "I called you yesterday." },
      { en: "morning", tr: "sabah", example: "I study English in the morning." },
      { en: "evening", tr: "akşam", example: "We watch TV in the evening." },
      { en: "night", tr: "gece", example: "Good night, sleep well." },
      { en: "hour", tr: "saat (süre)", example: "The film is two hours long." },
      { en: "minute", tr: "dakika", example: "Wait a minute, please." },
      { en: "early", tr: "erken", example: "I wake up early on Mondays." },
      { en: "late", tr: "geç", example: "Sorry, I'm late." },
    ],
  },
  {
    id: "food",
    title: "Yiyecek ve içecek",
    words: [
      { en: "food", tr: "yiyecek", example: "Turkish food is delicious." },
      { en: "water", tr: "su", example: "Drink a lot of water every day." },
      { en: "bread", tr: "ekmek", example: "We buy fresh bread every morning." },
      { en: "milk", tr: "süt", example: "There is no milk in the fridge." },
      { en: "egg", tr: "yumurta", example: "I eat two eggs for breakfast." },
      { en: "cheese", tr: "peynir", example: "This cheese is from Denizli." },
      { en: "meat", tr: "et", example: "He doesn't eat meat." },
      { en: "chicken", tr: "tavuk", example: "We had chicken for lunch." },
      { en: "fish", tr: "balık", example: "Fish is good for your health." },
      { en: "fruit", tr: "meyve", example: "Eat fruit instead of sugar." },
      { en: "vegetable", tr: "sebze", example: "Vegetables are cheap in summer." },
      { en: "breakfast", tr: "kahvaltı", example: "Breakfast is my favorite meal." },
      { en: "lunch", tr: "öğle yemeği", example: "Let's have lunch together." },
      { en: "dinner", tr: "akşam yemeği", example: "Dinner is ready!" },
      { en: "delicious", tr: "lezzetli", example: "This soup is delicious." },
    ],
  },
  {
    id: "places",
    title: "Yerler ve şehir",
    words: [
      { en: "house", tr: "ev", example: "Our house has a small garden." },
      { en: "home", tr: "ev, yuva", example: "I work from home." },
      { en: "school", tr: "okul", example: "The school is near our house." },
      { en: "hospital", tr: "hastane", example: "She works at a hospital." },
      { en: "shop", tr: "dükkân", example: "The shop opens at nine." },
      { en: "market", tr: "pazar, market", example: "We go to the market on Sundays." },
      { en: "street", tr: "cadde, sokak", example: "I live on this street." },
      { en: "city", tr: "şehir", example: "Denizli is a beautiful city." },
      { en: "country", tr: "ülke", example: "Which country are you from?" },
      { en: "restaurant", tr: "restoran", example: "This restaurant is always full." },
      { en: "park", tr: "park", example: "We walk in the park every evening." },
      { en: "airport", tr: "havalimanı", example: "The airport is far from here." },
      { en: "station", tr: "istasyon, durak", example: "The bus station is over there." },
      { en: "office", tr: "ofis", example: "My office is on the third floor." },
    ],
  },
  {
    id: "adjectives-1",
    title: "Temel sıfatlar 1",
    words: [
      { en: "good", tr: "iyi", example: "That's a good idea." },
      { en: "bad", tr: "kötü", example: "The weather is bad today." },
      { en: "big", tr: "büyük", example: "They live in a big house." },
      { en: "small", tr: "küçük", example: "I have a small car." },
      { en: "new", tr: "yeni", example: "I love my new phone." },
      { en: "old", tr: "eski, yaşlı", example: "This is an old building." },
      { en: "happy", tr: "mutlu", example: "She looks very happy today." },
      { en: "sad", tr: "üzgün", example: "Why are you sad?" },
      { en: "easy", tr: "kolay", example: "This exercise is easy." },
      { en: "difficult", tr: "zor", example: "English is not difficult." },
      { en: "hot", tr: "sıcak", example: "It's very hot in summer." },
      { en: "cold", tr: "soğuk", example: "The water is too cold." },
      { en: "fast", tr: "hızlı", example: "This train is very fast." },
      { en: "slow", tr: "yavaş", example: "Speak slowly, please." },
    ],
  },
  {
    id: "adjectives-2",
    title: "Temel sıfatlar 2",
    words: [
      { en: "beautiful", tr: "güzel", example: "Pamukkale is a beautiful place." },
      { en: "expensive", tr: "pahalı", example: "This jacket is too expensive." },
      { en: "cheap", tr: "ucuz", example: "The tickets are cheap today." },
      { en: "important", tr: "önemli", example: "Listening is very important." },
      { en: "interesting", tr: "ilginç", example: "This podcast is interesting." },
      { en: "boring", tr: "sıkıcı", example: "The meeting was boring." },
      { en: "tired", tr: "yorgun", example: "I'm tired after work." },
      { en: "hungry", tr: "aç", example: "I'm hungry. Let's eat something." },
      { en: "thirsty", tr: "susamış", example: "Are you thirsty? Here is water." },
      { en: "busy", tr: "meşgul", example: "I'm busy this afternoon." },
      { en: "free", tr: "boş, ücretsiz", example: "Are you free tomorrow?" },
      { en: "ready", tr: "hazır", example: "Dinner is ready." },
      { en: "same", tr: "aynı", example: "We work at the same company." },
      { en: "different", tr: "farklı", example: "Every language is different." },
    ],
  },
  {
    id: "work",
    title: "İş ve teknoloji",
    words: [
      { en: "job", tr: "iş, meslek", example: "She has a new job." },
      { en: "money", tr: "para", example: "Time is money." },
      { en: "meeting", tr: "toplantı", example: "The meeting starts at ten." },
      { en: "computer", tr: "bilgisayar", example: "I work on my computer all day." },
      { en: "phone", tr: "telefon", example: "My phone is ringing." },
      { en: "email", tr: "e-posta", example: "Send me an email, please." },
      { en: "message", tr: "mesaj", example: "I got your message." },
      { en: "question", tr: "soru", example: "I have a question." },
      { en: "problem", tr: "sorun", example: "No problem, I can fix it." },
      { en: "idea", tr: "fikir", example: "That's a great idea!" },
      { en: "company", tr: "şirket", example: "He works for an American company." },
      { en: "customer", tr: "müşteri", example: "The customer is always right." },
      { en: "team", tr: "takım, ekip", example: "Our team works well together." },
      { en: "project", tr: "proje", example: "We finished the project on time." },
    ],
  },
  {
    id: "weather-nature",
    title: "Hava ve doğa",
    words: [
      { en: "weather", tr: "hava durumu", example: "The weather is nice today." },
      { en: "sun", tr: "güneş", example: "The sun rises early in June." },
      { en: "rain", tr: "yağmur", example: "I love the smell of rain." },
      { en: "snow", tr: "kar", example: "There is snow on the mountains." },
      { en: "wind", tr: "rüzgâr", example: "The wind is strong today." },
      { en: "cloud", tr: "bulut", example: "There are dark clouds in the sky." },
      { en: "sky", tr: "gökyüzü", example: "The sky is clear tonight." },
      { en: "sea", tr: "deniz", example: "We swim in the sea in summer." },
      { en: "mountain", tr: "dağ", example: "The mountains are covered in snow." },
      { en: "tree", tr: "ağaç", example: "There is a big tree in the garden." },
      { en: "flower", tr: "çiçek", example: "She bought flowers for her mother." },
      { en: "animal", tr: "hayvan", example: "Dogs are loyal animals." },
    ],
  },
  {
    id: "common-phrases",
    title: "Sık kalıplar",
    words: [
      { en: "of course", tr: "tabii ki", example: "Of course you can come with us." },
      { en: "excuse me", tr: "affedersiniz", example: "Excuse me, where is the bank?" },
      { en: "I'm sorry", tr: "özür dilerim", example: "I'm sorry, I'm late." },
      { en: "thank you", tr: "teşekkür ederim", example: "Thank you for your help." },
      { en: "you're welcome", tr: "rica ederim", example: "You're welcome, anytime." },
      { en: "how about", tr: "-e ne dersin", example: "How about a coffee break?" },
      { en: "by the way", tr: "bu arada", example: "By the way, how is your family?" },
      { en: "for example", tr: "örneğin", example: "I like fruit, for example apples." },
      { en: "at least", tr: "en azından", example: "Listen for at least thirty minutes." },
      { en: "a little", tr: "biraz", example: "I speak a little English." },
      { en: "a lot", tr: "çok", example: "I learned a lot this month." },
      { en: "right now", tr: "şu anda", example: "I'm busy right now." },
      { en: "see you later", tr: "sonra görüşürüz", example: "I have to go. See you later!" },
    ],
  },
];
